workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.ipa
