name: bonanza777
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  webview_flutter: ^2.0.14
  flutter_displaymode: ^0.6.0
  http: ^0.13.3  
  wakelock_plus: ^1.2.7  
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/loader.gif
  uses-material-design: true
